# Site settings
author: Brian 
title: Brief Thoughts on Big Data
header-img: img/home-bg.png
email: bcaterfino@gmail.com
copyright_name: Brian 
description: > # this means to ignore newlines until "baseurl:"
  Bringing Data to Life
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bcat12

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
